/*
 * huangzongzhe
 * 2018.08.27
 */
import React, { Component } from 'react'
import NavNormal from '../../../NavNormal/NavNormal'
import style from './pages.scss'
// React component
class WhatIsPrivatePublicKey extends Component {
	render() {
		return (
			<div>
				<NavNormal></NavNormal>
				<div className={style.textContainer}>
					{/*<h2>什么是公钥私钥？</h2>*/}
					{/*<p>钱包中资金的控制取决于相应私钥的所有权和控制权。</p>*/}
					{/*<p>在区块链交易中，私钥用于生成支付货币所必须的签名，以证明资金的所有权。私钥必须始终保持机密，因为一旦泄露给第三方，相当于该私钥保护下的资产也拱手相让了。</p>*/}
					{/*<p>它不同于keystore，keystore是加密过后的私钥文件，只要密码强度足够强，即使黑客攻击，破译难度也很高。私钥实际上并不是存储在网络中，而是由用户生成并储存在一个文件或者简单的数据库中，称为钱包。用户的钱包地址就是由私钥通过椭圆曲线加密生成公钥，进而生成以0x开头的42位地址。</p>*/}
					{/*<p>私钥的样式为64位16进制哈希值字符串。</p>*/}
                    <h2>What is public key and private key？</h2>
                    <p>The control of funds in a wallet depends on the ownership and control of the private key.</p>
                    <p>In block-chain transactions, the private key is used to generate the signature necessary for the payment currency to prove the ownership of the fund. Private keys must always be kept confidential, because once they are disclosed to a third party, assets protected by the private key are also compromised.</p>
                    <p>It is different from keystore, which is a private key file after encryption. As long as the password strength is strong enough, even hackers attack, it is very difficult to decipher. The private key is not actually stored in the network, but is generated and stored by the user in a file or a simple database, called a wallet. The user's wallet address is generated by the private key through the elliptic curve encryption to generate the public key, and then generate the 36-bit address.</p>
                    <p>The style of the private key is a 64 bit 16 binary hash value string.</p>
				</div>
			</div>
		);
	}
}

export default WhatIsPrivatePublicKey;